### ISSUE TITLE
base64 encoded emails

### ISSUE THREAD

**Issue by lydiastepanek** [crisp-oss/email-forward-parser#14]
Hello, I'm using your library in my side project, [IsThisPhishy.io](https://isthisphishy.io/). (For context, I wrote a blog post where I mention using your library to parse forwarded emails: https://www.lydiaoncybersecurity.com/launching-isthisphishy/ .)

I noticed that your library is unable to parse base64 encoded emails, so it won't work on Outlook emails. Any plans to add support for this?

**Comment by eliottvincent** [comment]
Hey Lydia, cool project!

This library expects an already decoded email, so base64 won't work indeed. I highly suggest using something like https://github.com/nodemailer/mailparser first, in order to parse the emails you receive on help@isthisphishy.io.

This'll clean a lot of stuff (including base64 encoded emails). Then you can pass the result in `new EmailForwardParser().read(MY_EMAIL_STRING)` 😉

**Comment by lydiastepanek** [comment]
oh gotcha, that worked thanks!
